baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Harsh Vardhan'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  description = "Researcher working on NLP, algorithms, and language"
  email = "harsh25001@iiitd.ac.in"
  github = "mus49"
  twitter = "hvmahto"
